### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by valkyrienyanko** [valkyrienyanko/FirstTry#2]
No one has created an issue for this so I will open one myself.

There is a chance that the mod will crash when you reforge an item. The reason for this is unknown. Any help on this issue is greatly appreciated.

**Comment by Catbuttes** [comment]
It looks as though you are going beyond your defined array bounds when you are trying to access them via `rand.Next`. As an example, in reforge.cs you have the definition
```csharp
static int[] accessoryModifiers = { PrefixID.Warding, PrefixID.Menacing, PrefixID.Quick, PrefixID.Lucky, PrefixID.Arcane };
```
which has a length of 5. You then access it using 
```csharp
int index = rand.Next(0, accessoryModifiers.Length);
                return accessoryModifiers[index];
```
which will return a value between 0-5 inclusive for a total of **6** options. As C# indexes arrays from 0, if you attempt to access the element at `array.Length` then you are always going to be beyond the bounds of the array. in the given example, you want to change the call to rand.Next to
```csharp
int index = rand.Next(0, accessoryModifiers.Length-1);
                return accessoryModifiers[index];
```

This will need doing in all places where you are making references to arrays as any one of them could cause a crash.

**Comment by valkyrienyanko** [comment]
I did what you said.

After further testing I found out that the Lightning Aura Rod (Summon) crashes when given a mythical modifier but not demonic modifier but the Flameburst Rod (Summon) can take either mythical or demonic modifier without crashing.

Every other damage type seems fine with no crashes.

**Comment by valkyrienyanko** [comment]
It seems like the array.Length - 1 code you suggested had no effect on the crash and in fact just took away 1 from the actual array and never went out side bounds in the first place.

**Comment by valkyrienyanko** [comment]
The mystical modifier seems to be like the only issue here so I replaced it with the demonic modifier and am no longer get any problems.
