### ISSUE TITLE
 Reforge drills crashes the game

### ISSUE THREAD

**Issue by Mikeliro** [valkyrienyanko/FirstTry#5]
When I try to forge any drill, the game crashes.
I tested almost all of them.
And the error occurred in all that I tested.

https://cdn.discordapp.com/attachments/647981212643622912/647982502803144704/unknown.png
https://cdn.discordapp.com/attachments/647981212643622912/647982591294570509/unknown.png

**Comment by steviegt6** [comment]
Was fixed in 2.2.
